"""Add documents models and document_categories table

Revision ID: 3336ed844a79
Revises: 23b7d269978c
Create Date: 2025-11-12 18:47:47.251821

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3336ed844a79'
down_revision: Union[str, Sequence[str], None] = '23b7d269978c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('documents',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('content_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_indexed', sa.Boolean(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index(op.f('ix_documents_title'), 'documents', ['title'], unique=False)
    op.create_index(op.f('ix_documents_upload_date'), 'documents', ['upload_date'], unique=False)
    op.drop_table('document')

    # Insert seed data for document categories
    from sqlalchemy import table, column
    from sqlalchemy import String, DateTime

    document_categories_table = table(
        'document_categories',
        column('name', String),
        column('description', String),
        column('created_at', DateTime)
    )

    op.bulk_insert(document_categories_table, [
        {
            'name': 'Políticas RRHH',
            'description': 'Documentos de políticas de recursos humanos, beneficios, contratación y gestión de personal',
            'created_at': datetime.now(timezone.utc)
        },
        {
            'name': 'Procedimientos Operativos',
            'description': 'Manuales de procedimientos estándar, guías operativas y procesos de negocio',
            'created_at': datetime.now(timezone.utc)
        },
        {
            'name': 'Manuales Técnicos',
            'description': 'Documentación técnica, especificaciones, manuales de usuario y guías de sistemas',
            'created_at': datetime.now(timezone.utc)
        },
        {
            'name': 'FAQs',
            'description': 'Preguntas frecuentes, guías de solución de problemas y respuestas a consultas comunes',
            'created_at': datetime.now(timezone.utc)
        },
        {
            'name': 'Normativas',
            'description': 'Regulaciones, normativas legales, estándares de cumplimiento y requerimientos regulatorios',
            'created_at': datetime.now(timezone.utc)
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Clean up seeded data first
    op.execute("DELETE FROM document_categories")

    op.create_table('document',
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(), nullable=False),
    sa.Column('upload_date', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.drop_index(op.f('ix_documents_upload_date'), table_name='documents')
    op.drop_index(op.f('ix_documents_title'), table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('document_categories')
    # ### end Alembic commands ###
