"""Add quiz and quiz_questions tables

Revision ID: c60c6bbff85b
Revises: add_generated_content_table
Create Date: 2025-11-14 10:41:07.179850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c60c6bbff85b'
down_revision: Union[str, Sequence[str], None] = 'add_generated_content_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sa.String(20), nullable=False),  # Store difficulty as string for SQLite compatibility
    sa.Column('num_questions', sa.Integer(), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_created_at'), 'quiz', ['created_at'], unique=False)
    op.create_index(op.f('ix_quiz_difficulty'), 'quiz', ['difficulty'], unique=False)
    op.create_index(op.f('ix_quiz_document_id'), 'quiz', ['document_id'], unique=False)
    op.create_index(op.f('ix_quiz_user_id'), 'quiz', ['user_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=False),
    sa.Column('correct_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(20), nullable=False),  # Store difficulty as string for SQLite compatibility
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_created_at'), 'quiz_questions', ['created_at'], unique=False)
    op.create_index(op.f('ix_quiz_questions_quiz_id'), 'quiz_questions', ['quiz_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_questions_quiz_id'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_created_at'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_quiz_user_id'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_document_id'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_difficulty'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_created_at'), table_name='quiz')
    op.drop_table('quiz')
    # ### end Alembic commands ###
