"""Add admin validation and soft delete fields to generated_content

Revision ID: cebc7701286d
Revises: add_quiz_attempts_table
Create Date: 2025-11-14 16:02:03.524206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'cebc7701286d'
down_revision: Union[str, Sequence[str], None] = 'add_quiz_attempts_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add validation fields to generated_content
    op.add_column('generated_content', sa.Column('is_validated', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('generated_content', sa.Column('validated_by', sa.Integer(), nullable=True))
    op.add_column('generated_content', sa.Column('validated_at', sa.DateTime(), nullable=True))
    op.add_column('generated_content', sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # Create indexes
    op.create_index(op.f('ix_generated_content_deleted_at'), 'generated_content', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_generated_content_is_validated'), 'generated_content', ['is_validated'], unique=False)

    # Add foreign key for validated_by
    op.create_foreign_key(None, 'generated_content', 'user', ['validated_by'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generated_content', type_='foreignkey')
    op.drop_index(op.f('ix_generated_content_is_validated'), table_name='generated_content')
    op.drop_index(op.f('ix_generated_content_deleted_at'), table_name='generated_content')
    op.create_index(op.f('ix_generated_content_doc_type_created'), 'generated_content', ['document_id', 'content_type', 'created_at'], unique=False)
    op.alter_column('generated_content', 'content_type',
               existing_type=sa.Enum('SUMMARY', 'QUIZ', 'LEARNING_PATH', name='contenttype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('generated_content', 'deleted_at')
    op.drop_column('generated_content', 'validated_at')
    op.drop_column('generated_content', 'validated_by')
    op.drop_column('generated_content', 'is_validated')
    op.drop_index(op.f('ix_learning_paths_user_level'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_user_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_topic'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_created_at'), table_name='learning_paths')
    op.drop_table('learning_paths')
    # ### end Alembic commands ###
